name: chocolatine

on: push

env:
  EXECUTABLES: ""

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: check coding style
        uses: actions/checkout@v3
      - name: Run coding style
        run:
          check.sh $(pwd) $(pwd)
      - name: parse and display
        if: always()
        run: |
          if [ -f coding-style-reports.log ]; then
            while read line; do
              file=$(echo $line | cut -d ':' -f 1)
              nb=$(echo $line | cut -d ':' -f 2)
              type=$(echo $line | cut -d ':' -f 3)
              err_code=$(echo $line | cut -d ':' -f 4)
              echo "::error title=${type} coding style error,file=${file},line={nb}::${err_code}"
            done < coding-style-reports.log
          fi
  
  check_program_compilation:
    runs_on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: check program compilation
        uses: actions/checkout@v3
        run: make
        timeout-minutes: 2
      - name: clean repo
        run: make clean
      - name: run program
        run: |
          read -a executable_list <<< "$EXECUTABLES"
          for executable in "${executable_list[@]}"; do
            ./$executable
          done
