name: chocolatine

on: push

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: check_coding_style
        uses: actions/checkout@v3
      - name: Run coding style
        run:
          check.sh $(pwd) $(pwd)
        run: |
        if [ -f coding-style-reports.log ]; then
          while read line; do
            f = $(echo $(line) | cut -d ':' -f 1)
            nb = $(echo $(line) | cut -d ':' -f 2)
            type = $(echo $(line) | cut -d ':' -f 3)
            err_code = $(echo $(line) | cut -d ':' -f 4)
            echo "::error title=${type} coding style error, f=${f}, line={nb}"
          done > coding-style-reports.log
        fi
        